version: "3.9"

services: 
    db:
        image: postgres
        volumes: 
            - ./database:/var/lib/postgresql/data
        environment: 
            # Gets variables from .env file for configuration
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports: 
            - 5433:5432
    api:
        build: ./backend
        command: gunicorn --reload -b 0.0.0.0:8000 CloudReaderApi.wsgi 
        volumes: 
            - ./backend:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db
        env_file: 
            - .env
    client:
        build: ./frontend
        command: npm start
        volumes:
            - ./frontend:/app
        ports: 
            - 3000:3000
        depends_on: 
            - api
        env_file: 
            - .env
    